# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import src.shared.types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnetwork.proto\x12\x07network\x1a\x0btypes.proto\"A\n\x17ListSyncFoldersResponse\x12&\n\x0bsyncFolders\x18\x01 \x03(\x0b\x32\x11.types.SyncFolder\"\x16\n\x14\x41\x64\x64SyncFolderRequest\"\x19\n\x17RemoveSyncFolderRequest\"\x12\n\x10StartSyncRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LISTSYNCFOLDERSRESPONSE']._serialized_start=39
  _globals['_LISTSYNCFOLDERSRESPONSE']._serialized_end=104
  _globals['_ADDSYNCFOLDERREQUEST']._serialized_start=106
  _globals['_ADDSYNCFOLDERREQUEST']._serialized_end=128
  _globals['_REMOVESYNCFOLDERREQUEST']._serialized_start=130
  _globals['_REMOVESYNCFOLDERREQUEST']._serialized_end=155
  _globals['_STARTSYNCREQUEST']._serialized_start=157
  _globals['_STARTSYNCREQUEST']._serialized_end=175
# @@protoc_insertion_point(module_scope)
