# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
    branches: [ "release" ]
  push:
    branches: [ "release" ]

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest numpy
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: Nuitka/Nuitka-Action@main
      with:
          nuitka-version: main
          script-name: main.py
          mingw64: true
    - name: Generate release tag
      id: generate_release_tag
      uses: amitsingh-007/next-release-tag@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: 'v'
        tag_template: 'yyyy.mm.dd.i'
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: ${{ steps.generate_release_tag.outputs.next_release_tag }}
        prerelease: false
        title: Release ${{ steps.generate_release_tag.outputs.next_release_tag }}
        files: |
          README.md
          build/*.exe
          *.cmd
          
          
          
          
          
          
          
          
          
          
