name: Check Semantic Commit

on:
  pull_request:
    branches: [ "release" ]

jobs:
  check-semantic-commit:
    name: Validate PR title

    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
